name: Psalm

on:
  push:
    paths:
      - '**.php'
      - 'psalm*'

jobs:
  psalm:
    name: psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json') }}

      - name: Run composer install
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_4_LICENSE_KEY }}"
          composer install -n --prefer-dist

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - run: composer global require cpx/cpx

      - name: Run Psalm
        run: composer psalm -- --shepherd
